- _target_: loss.components.BasicClassificationLoss
  name: ce_loss
  weight: 1.0
  base_loss:
    _target_: torch.nn.CrossEntropyLoss

- _target_: loss.components.HaltingCrossEntropy
  name: trm_cutoff_loss
  weight: 1.0
  base_loss:
    _target_: torch.nn.CrossEntropyLoss

- _target_: loss.components.PercentCorrect
  name: correct_ratio_metric
  weight: 1.0
