defaults:
  - _self_
  - data: standard_module
  - learning: standard
  - optimizer: adamw_standard
  - scheduler: none
  - loss: trm
  - model: trm
  - module: trm_cls

project_name: LightningTemplate
model_name: mnist_fcn
resume: null

# Optimizations
use_torch_compile: False

