defaults:
  - _self_
  - data: dllm
  - learning: standard
  - optimizer: adamw_standard
  - scheduler: none
  - loss: dllm
  - model: dllm
  - module: dllm

project_name: LightningTemplate
model_name: dllm
resume: null

# Optimizations
use_torch_compile: False
