defaults:
  - _self_
  - data: dllm
  - learning: standard
  - optimizer: adamw_standard
  - scheduler: one_cycle_lr
  - loss: dllm
  - model: trm_dllm
  - module: trm_dllm

project_name: LightningTemplate
model_name: dllm
resume: null

# Optimizations
use_torch_compile: False
seq_length: 256
